Sprint 6 solution
atroshchenkoya/java-kanban pull request #1
Opened 2024-09-22 19:45 UTC by atroshchenkoya

2024-09-23 22:43 UTC, NikolaiDem requested changes
Еще нужны тесты для менеджера истории.
Дополнительно включить тесты:
  1) удаляется 1-ая нода
  2) удаляется последняя нода
  3) удаляется промежуточная нода
  4) добавляется задача, которая уже есть в истории
  5) история пуста, и в нее добавляется 1-ый элемент
  6) когда удаляется первый и единственный элемент

2024-09-23 22:43 UTC, NikolaiDem commented on src/entity/util/CustomLinkedList.java
> +    CustomNode head;
Лучше сделать его внутренним классом InMemoryHistoryManager, чтобы логика не размазывалась по пакету.
Еще хороший вариант сделать так, чтобы методы CustomLinkedList работали только с объектами Task, но не CustomNode

2024-09-23 22:43 UTC, NikolaiDem commented on src/interfaces/HistoryManager.java
>  public interface HistoryManager {
Еще нужен метод для удаления таски

2024-09-23 22:43 UTC, NikolaiDem commented on src/managers/InMemoryHistoryManager.java
>      public List<Task> getHistory() {
Лучше избавиться от while(true)

    @Override
    public List<Task> getHistory() {
        List<Task> viewedTasks = new ArrayList<>();
        CustomNode node = historyList.getHead();

        while (node != null) {
            viewedTasks.add(node.getTask());
            node = node.getNextNode();
        }
        return viewedTasks;
    }

2024-09-24 08:15 UTC, atroshchenkoya commented on src/managers/InMemoryHistoryManager.java
>      public List<Task> getHistory() {
Поправил + дропнул проверку

2024-09-24 08:23 UTC, atroshchenkoya commented on src/entity/util/CustomLinkedList.java
> +    CustomNode head;
Класс перетащил, поправил, чтобы методы CustomLinkedList в качестве аргументов таски принимали. 

Лучше, наверное, было бы вообще целиком логику добавления таски в CustomLinkedList засунуть(включая поиск и дроп старой), но тогда метод CustomLinkedList.remove правильно будет делать приватным, чтобы скрыть метод, доступа к которому по-хорошему из-вне не должно быть. А мы его зачем-то должны в интерфейс вытащить. Немного криво получается как ни крути.

2024-09-24 08:28 UTC, atroshchenkoya commented on src/interfaces/HistoryManager.java
>  public interface HistoryManager {
Добавил метод прямого удаления таски из истории в интерфейс и переопределил в реализации

2024-09-25 08:18 UTC, NikolaiDem approved these changes

2024-09-25 08:38 UTC, merged