sprint 8 - core logic and tests
atroshchenkoya/java-kanban pull request #3
Opened 2024-10-19 14:52 UTC by atroshchenkoya

По идее алгоритм поиска коллизий по времени за константу должен отрабатывать.

Еще отрефачу места, где используются форычи и форы...

2024-10-20 22:22 UTC, NikolaiDem commented
> По идее алгоритм поиска коллизий по времени за константу должен отрабатывать.
Отрабатывать за константу не может, так как методы lower higher логарифмические

2024-10-20 22:26 UTC, NikolaiDem requested changes

2024-10-20 22:26 UTC, NikolaiDem commented on src/managers/InMemoryTaskManager.java
> +            checkTimeCollision(taskToCreate);
Наверное, сначала нужно проверить коллизии, а потом добавлять в мапу.
Аналогично для сабтасок

2024-10-20 22:26 UTC, NikolaiDem commented on src/managers/InMemoryTaskManager.java
> +        sortedTasksAndSubTasks.remove(task);
Удалять нужно старую таску, а не новую.
Аналогично для сабтасок

2024-10-20 22:26 UTC, NikolaiDem commented on src/managers/InMemoryTaskManager.java
> +    private void checkTimeCollision(Task task) {
Альтернативное решение с меньшей когнитивной нагрузкой )

    private void checkTimeCollision(Task task) {
        var closestEndTime = Optional.ofNullable(sortedTasksAndSubTasks.lower(task))
                .map(Task::getEndTime)
                .orElse(LocalDateTime.MIN);
        var closestStartTime = Optional.ofNullable(sortedTasksAndSubTasks.higher(task))
                .map(Task::getStartTime)
                .orElse(LocalDateTime.MAX);
        if (closestEndTime.isAfter(task.getStartTime()) || task.getEndTime().isAfter(closestStartTime)) {
            throw new TimeCollisionException(task);
        }
    }

2024-10-21 07:49 UTC, atroshchenkoya commented on src/managers/InMemoryTaskManager.java
> +            checkTimeCollision(taskToCreate);
Точно... Я сначала сделал информационным сообщение о коллизии, поэтому оно осталось за добавлением. А потом поменял на Exception, а про вызов забыл уже.
В итоге все чуть веселее - получается подобие транзакции:
1) Добавляем в TreeSat
2) Проверяем, что нет коллизий
3) Если есть - откатываем добавление
4) Кидаем исключение, в хранилище элемент не добавляем, обновление не проводим

Если просто местами поменять - надо дописывать код внутри метода checkTimeCollision, чтобы он с копией сета работал. Это экономия по строчкам кода, но каждый раз копировать сет, если он будет огромный... В общем пока выбираю первый вариант с подобием транзакции.

2024-10-21 08:31 UTC, atroshchenkoya commented on src/managers/InMemoryTaskManager.java
> +        sortedTasksAndSubTasks.remove(task);
Тут не важно старый или новый объект ставить, у них айдишники одинаковые, equals и hashCode переопределен на анализ исключительно ID у объекта. Поэтому и удалит он правильный элемент, и добавит правильный. Но опять же - ремув, да и апдейт таски в принципе не должен отрабатывать, если пришло кривое время в обновлении - это я поправил.

2024-10-21 08:50 UTC, atroshchenkoya commented on src/managers/InMemoryTaskManager.java
> +    private void checkTimeCollision(Task task) {
Красота) Не знал, что к Optional можно map применять, теперь знаю. Стащил себе в код, спасибо))

2024-10-21 09:47 UTC, NikolaiDem commented on src/managers/InMemoryTaskManager.java
>      public void updateTask(Task task) {
Добавить тесты на методы обновления времени в таске

2024-10-21 09:48 UTC, NikolaiDem commented on test/managers/InMemoryTaskManagerTest.java
> +        Assertions.assertEquals(subTask3,taskManager.getPrioritizedTasks().get(2));
Такие проверки не информативны, так как проверяют только id

2024-10-21 09:50 UTC, NikolaiDem commented on src/managers/InMemoryTaskManager.java
> +        sortedTasksAndSubTasks.remove(task);
Технически все верно. Осталось определить корректную форму equals/hashcode

2024-10-21 16:01 UTC, NikolaiDem requested changes
Нужны тесты для обновления

2024-10-21 18:51 UTC, atroshchenkoya commented on test/managers/InMemoryTaskManagerTest.java
> +        Assertions.assertEquals(subTask3,taskManager.getPrioritizedTasks().get(2));
В рамках данного теста проверяется, что сортировка корректно отработала и верный порядок айдишников отдал getPrioritizedTasks(). Пару проверок добавлю для значений полей)

2024-10-21 19:33 UTC, atroshchenkoya commented on src/managers/InMemoryTaskManager.java
>      public void updateTask(Task task) {
К превеликому сожалению, все-таки ускорить перебор TreeSet не выйдет - алгоритм с верхним и нижним нодами не учитывает кейса, когда в мапу засунули равный уже существующему в мапе объект по компаратору.)) Но код с нодами красивый, я бы его оставил..
Тесты добавил..

2024-10-22 06:50 UTC, atroshchenkoya commented on src/managers/InMemoryTaskManager.java
>      public void updateTask(Task task) {
Я тут подумал немного - если бы мы использовали TreeMap и ключом бы сделали время начала - работала бы изначально задуманная логика с поиском по верхней и нижней ноде без дополнительного перебора мапы. Потому что наличие ключа(времени) можно было бы проверить.

2024-10-22 09:23 UTC, NikolaiDem commented on src/managers/InMemoryTaskManager.java
>      public void updateTask(Task task) {
А можно в sortedTasksAndSubTasks не добавлять taskToCreate перед проверкой checkTimeCollision()?

2024-10-22 09:44 UTC, NikolaiDem commented on test/managers/InMemoryTaskManagerTest.java
>  }
Почему не работает тест:

    @Test
    void checkMultipleUpdate() {
        LocalDateTime now = LocalDateTime.now();
        Duration duration = Duration.ofMillis(1);
        Task initialTask = new Task(0, "task", "desc", TaskStatus.IN_PROGRESS, now.plus(duration), duration);
        taskManager.createTask(initialTask);
        Stream.iterate(0, i -> i + 1)
                .limit(10_000)
                .map(i -> new Task(initialTask.getId(), "task" + i, "desc" + i, TaskStatus.IN_PROGRESS, now.plus(duration.multipliedBy(i + 2)), duration))
                .forEach(taskManager::updateTask);

        assertEquals(1, taskManager.getPrioritizedTasks().size());
    }

2024-10-22 16:54 UTC, atroshchenkoya commented on src/managers/InMemoryTaskManager.java
>      public void updateTask(Task task) {
В этом случае придется как раз перебрать sortedTasksAndSubTasks на поиск коллизий и точных совпадений дат времени начала

2024-10-22 17:02 UTC, atroshchenkoya commented on test/managers/InMemoryTaskManagerTest.java
>  }
Не предполагается, что можно оперировать миллисекундой. Скорее всего, это ушатывает логику, сейчас проверю и отвечу...

2024-10-22 17:19 UTC, atroshchenkoya commented on test/managers/InMemoryTaskManagerTest.java
>  }
В общем, вот ответ [https://ru.stackoverflow.com/questions/582091/%D0%A3%D0%B4%D0%B0%D0%BB%D1%8F%D0%B5%D1%82-%D0%BB%D0%B8-treeset-%D0%BF%D0%BE%D0%B2%D1%82%D0%BE%D1%80%D0%B5%D0%BD%D0%B8%D1%8F](url)

Сейчас исправлю..

2024-10-22 17:29 UTC, atroshchenkoya commented on test/managers/InMemoryTaskManagerTest.java
>  }
TreeSet анализирует не по equals, а по компоратору уникальность. В общем случае мы этого не видим, так как часто в компараторе переиспользуют логику equals, но у нас не так, поэтому бардак вышел..

2024-10-22 19:00 UTC, atroshchenkoya commented on test/managers/InMemoryTaskManagerTest.java
>  }
Переделал логику. Тест новый добавил в копилку.
Дополнительно сделал так, чтобы приорити сет тоже откатывался после обновления, если в него попала кривая таска, вызвавшая коллизию. Спасибо за тест!

2024-10-22 19:05 UTC, atroshchenkoya commented on src/managers/InMemoryTaskManager.java
>      public void updateTask(Task task) {
Кстати, я тут прочитал, что, конечно же можно))) Методы TreeSet, которые мы используем, не обязательно принимают тот элемент, который у коллекции уже есть.
Взгляну на уже починенный код с этим знанием)

2024-10-22 19:22 UTC, atroshchenkoya commented on src/managers/InMemoryTaskManager.java
>      public void updateTask(Task task) {
Около 30 строк кода удалилось, круто)

2024-10-22 20:58 UTC, NikolaiDem commented on test/managers/InMemoryTaskManagerTest.java
>  }
Задачу можно решить проще:

    @Override
    public void updateTask(Task task) {
        Task oldTask = taskStorage.get(task.getId());
        sortedTasksAndSubTasks.remove(oldTask);
        if (task.isScheduled()) {
            tryToUpdatePriorityTasks(task, oldTask);
        }
        taskStorage.put(task.getId(), task);
    }

    private void tryToUpdatePriorityTasks(Task task, Task oldTask) {
        if (hasTimeCollision(task)) {
            sortedTasksAndSubTasks.add(oldTask);
            throw new TimeCollisionException("!!!");
        } else {
            sortedTasksAndSubTasks.add(task);
        }
    }

    private boolean hasTimeCollision(Task task) {
        var closestEndTime = Optional.ofNullable(sortedTasksAndSubTasks.lower(task))
                .map(Task::getEndTime)
                .orElse(LocalDateTime.MIN);
        var closestStartTime = Optional.ofNullable(sortedTasksAndSubTasks.higher(task))
                .map(Task::getStartTime)
                .orElse(LocalDateTime.MAX);
        return closestEndTime.isAfter(task.getStartTime()) || task.getEndTime().isAfter(closestStartTime);
    }

2024-10-22 21:02 UTC, NikolaiDem approved these changes

2024-10-22 21:59 UTC, atroshchenkoya commented on test/managers/InMemoryTaskManagerTest.java
>  }
- Добавил этот код, свалился тест
- Оказалось, что тест был кривой
- Но тест выкидывал не ту ошибку, которую ожидалось после починки теста
- Нашел багу, в своем старом коде поправил, как будет время, попробую отреффакторить в сторону предложенного варианта.
Спасибо!!!

2024-10-22 22:02 UTC, merged