Sprint 9 solution http api
atroshchenkoya/java-kanban pull request #6
Opened 2024-11-03 10:18 UTC by atroshchenkoya

Я в целом приложение отрефакторил в течение недели...
Буду благодарен за максимальное число комментариев.

2024-11-04 09:05 UTC, NikolaiDem requested changes

2024-11-04 09:05 UTC, NikolaiDem commented on src/ru/practicum/kanban/servers/handlers/BaseHttpHandler.java
> +        try {
Вместо явного h.close() лучше использовать try with resources
try (h){
            h.sendResponseHeaders(responseCode, resp.length);
            if (!text.isEmpty()) {
                h.getResponseBody().write(resp);
            }
        } catch (IOException e) {
            throw new HttpExchangeException(e);
        }

2024-11-04 09:05 UTC, NikolaiDem commented on src/ru/practicum/kanban/servers/handlers/EpicsHandler.java
> +                handleGetEpicById(exchange);
Если эпик по id не найден, то лучше вернуть 404.
Аналогично для тасок и сабтасок

2024-11-04 09:05 UTC, NikolaiDem commented on src/ru/practicum/kanban/servers/handlers/EpicsHandler.java
> +        if (taskManager.getEpic(epicId) == null) {
Вместо дополнительных проверок при обновлении удалении эпика лучше делать эти проверки в самом менеджере. Если входные данные невалидны, то бросить исключение непосредственно в самих методах менеджера. Аналогично для тасок и сабтасок

2024-11-04 09:05 UTC, NikolaiDem commented on src/ru/practicum/kanban/servers/handlers/HistoryHandler.java
> +            sendText(exchange, "This endpoint is not supported.", 400);
Если эндпоинт не найден, то 404

2024-11-04 09:05 UTC, NikolaiDem commented on src/ru/practicum/kanban/servers/handlers/PrioritizedHandler.java
> +            sendText(exchange, "This endpoint is not supported.", 400);
Если эндпоинт не найден, то 404

2024-11-04 09:05 UTC, NikolaiDem commented on src/ru/practicum/kanban/servers/handlers/adapters/DurationAdapter.java
> +    public Duration read(JsonReader in) throws IOException {
А при null входящем значении?

2024-11-04 09:05 UTC, NikolaiDem commented on src/ru/practicum/kanban/servers/handlers/adapters/LocalDateTimeAdapter.java
> +        return LocalDateTime.parse(in.nextString(), formatter);
А при null входящем значении?

2024-11-04 09:16 UTC, atroshchenkoya commented on src/ru/practicum/kanban/servers/handlers/BaseHttpHandler.java
> +        try {
Спасибо, поправил + название переменной поправил

2024-11-04 09:21 UTC, atroshchenkoya commented on src/ru/practicum/kanban/servers/handlers/EpicsHandler.java
> +                handleGetEpicById(exchange);
Спасибо, поправил для всех случаев, когда объекта нет.

2024-11-04 09:22 UTC, atroshchenkoya commented on src/ru/practicum/kanban/servers/handlers/HistoryHandler.java
> +            sendText(exchange, "This endpoint is not supported.", 400);
Поправил

2024-11-04 09:41 UTC, atroshchenkoya commented on src/ru/practicum/kanban/servers/handlers/PrioritizedHandler.java
> +            sendText(exchange, "This endpoint is not supported.", 400);
поправил везде

2024-11-04 10:11 UTC, atroshchenkoya commented on src/ru/practicum/kanban/servers/handlers/EpicsHandler.java
> +        if (taskManager.getEpic(epicId) == null) {
Это я поправил и обнаружил, что теперь некорректно работает история, так как наличие таски проверяется через лишний вызов, сейчас и это поправлю.

2024-11-04 12:22 UTC, atroshchenkoya commented on src/ru/practicum/kanban/servers/handlers/EpicsHandler.java
> +        if (taskManager.getEpic(epicId) == null) {
Исправил для всех методов всех объектов

2024-11-04 12:52 UTC, atroshchenkoya commented on src/ru/practicum/kanban/servers/handlers/adapters/DurationAdapter.java
> +    public Duration read(JsonReader in) throws IOException {
Добавил обработку null

2024-11-04 12:52 UTC, atroshchenkoya commented on src/ru/practicum/kanban/servers/handlers/adapters/LocalDateTimeAdapter.java
> +        return LocalDateTime.parse(in.nextString(), formatter);
Добавил обработку null

2024-11-04 13:50 UTC, atroshchenkoya commented
Есть еще один момент, который не ок, только я не знаю, стоит ли с этим в рамках данной работы разбираться.
У меня приложение не позволяет пользователю самому выбирать айдишник нового объекта. Но и после создания его не отдает. По-хорошему, надо отдавать его в теле ответа на создание.

2024-11-05 13:45 UTC, NikolaiDem approved these changes

2024-11-22 07:48 UTC, merged